apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: demo-cluster
  region: us-east-1

vpc:
  subnets:
    private:
      us-east-1c: { id: subnet-0db77c8a5d74da149 }
      us-east-1d: { id: subnet-0f184f2b2e9936220 }
      us-east-1a: { id: subnet-01f321a807bf51903 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: t2.mirco
    desiredCapacity: 2
    privateNetworking: true
  - name: ng-2-builders
    labels: { role: builders }
    instanceType: t2.micro
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
